# Page settings
baseurl = "/"
title = "freeCodeCamp Sacramento"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "info@freecodecampsacramento.org"
  # Navigation
  [params.navigation]
    brand = "freeCodeCamp Sacramento"
    about = "About"
    work = "Gallery"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Learn to Code with Sacramentans"
    subtitle = 'Join a Community of Learners'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Community"
    description = "Engage in a community of hundreds of Campers on our Facebook Group."
    url = "https://www.facebook.com/groups/free.code.camp.sacramento/"
    button = "Join"
    icon = "icon-people"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Events"
    description = "Want to meet fellow Campers? Come out to a Meetup event!"
    url = "https://www.meetup.com/freeCodeCamp-Sacramento/"
    button = "Upcoming Events"
    icon = "icon-calendar"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Proposal"
    description = "Have an idea? Want to submit or give a talk? We want to hear from you!"
    url = "#contact"
    button = "Submit"
    icon = "icon-bubble"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = ''
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=b_K0zM0EEnA"

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = "Here are some pictures from the events that we had in the past."
    footertext = ''

    [[params.work.row]]
      img = "coffee-and-code-tupelo.jpg"
      alt = "Campers being productive around a table at Tupelo Coffee House"
      title = "Coffee and Code Meetup"
      subtitle = "@ Tupelo Coffee House"

    [[params.work.row]]
      img = "arden-dimick-presentation.jpg"
      alt = "Ivan Villa is presenting his talk 'Professional Web Design Tips' in front of a large audience at the Arden-Dimick Library"
      title = "Presentation by Ivan Villa"
      subtitle = "@ Arden-Dimick Library"

    [[params.work.row]]
      img = "sfhtml5-google-sf.jpg"
      alt = "A group of Campers taking a picture in front of the Google sign at the SFHTML5 Meetup at Google San Francisco"
      title = "Fieldtrip to SFHTML5 Meetup"
      subtitle = "@ SFHTML5 - Google San Francisco"

    [[params.work.row]]
      img = "sfhtml5-sarah-drasner.jpg"
      alt = "A group of Campers taking a picture with guest speaker, Sarah Drasner, at the SFHTML5 Meetup at Google San Francisco"
      title = "Getting to meet Sarah Drasner"
      subtitle = "@ SFHTML5 - Google San Francisco"

    [[params.work.row]]
      img = "coffee-and-code-tupelo2.jpg"
      alt = "Campers sitting around a long wooden table and posing for a picture at Tupelo Coffee House"
      title = "Coffee and Code Meetup"
      subtitle = "@ Tupelo Coffee House"

    [[params.work.row]]
      img = "campers-beerjs.jpg"
      alt = "A group of Campers posing for a picture in an evening of socializing at the Midtown Der Biergarten"
      title = "Bonfire Afterhours"
      subtitle = "@ Midtown Der Biergarten"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "We're a friendly community of amazing and wonderful coders who are striving for a common purpose: to become a better developer. This meetup is for new and experienced developers who are working with freeCodeCamp's online courses, learning between beginner and intermediate computer science concepts, and want to engage in social interactions with their peers. Our main focus is to help you learn to code while having a good time!"

    # [[params.about.item]]
    #   name = "Billy Le"
    #   position = "Head Organizer"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person1.jpg"
    #   alt = "Person1"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-linkedin", "#"]
    #   ]

    # [[params.about.item]]
    #   name = "Rob Smith"
    #   position = "Web Developer"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person2.jpg"
    #   alt = "Person2"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-github", "#"]
    #   ]

    # [[params.about.item]]
    #   name = "Larry Ben"
    #   position = "Web Designer"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person3.jpg"
    #   alt = "Person3"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-dribbble", "#"]
    #   ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Send us your questions on anything from getting more information about our group to submitting an idea for a talk or workshop."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Sacramento, California, United States of America"],
        ["icon-envelope", "info@freecodecampsacramento.org"]
      ]

    name = "Name"
    email = "Email"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'We are not affiliated with freeCodeCamp and are an independent study group.'
